// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef POSIX_TRANSLATION_READONLY_FS_READER_TEST_H_
#define POSIX_TRANSLATION_READONLY_FS_READER_TEST_H_

#include <cstddef>

namespace posix_translation {

// A list of files |kTestFsImage| generated by create_test_fs_image.py contains.
const struct TestFile {
  const char* filename;
  const char* link_target;
  size_t size;
} kTestFiles[] = {
  { "/test/a.odex", NULL, 4U },  // "123\n"
  { "/test/big.odex", NULL, 100000U },  // '\0' x90000, then 'X' x10000
  { "/test/b.odex", NULL, 1U },  // "Z"
  { "/test/c0.odex", NULL, 0U },
  { "/test/c.odex", NULL, 0U },
  { "/test/dir/c.odex", NULL, 1U },  // "A"
  { "/test/dir/empty.odex", NULL, 0U },
  { "/test/emptyfile", NULL, 0U },
  { "/test/symlink1", "/test/a.odex", 0U },
  { "/test/symlink2", "/test/b.odex", 0U },
};
const size_t kNumTestFiles = arraysize(kTestFiles);

}  // namespace posix_translation
#endif  // POSIX_TRANSLATION_READONLY_FS_READER_TEST_H_
